<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-81ARGGN" failures="3" tests="6" name="Login Test - ff" time="157.907" errors="0" timestamp="2021-08-16T09:58:30 IST">
  <testcase classname="com.sg.test.LoginTest" name="invalidCredentialTest" time="3.305"/>
  <testcase classname="com.sg.test.LoginTest" name="invalidCredentialTest" time="1.463"/>
  <testcase classname="com.sg.test.LoginTest" name="invalidCredentialTest" time="1.631"/>
  <testcase classname="com.sg.test.LoginTest" name="validCredentialTest" time="4.636">
    <failure type="java.lang.AssertionError" message="expected [OpenEMR] but found [CloudEMR]">
      <![CDATA[java.lang.AssertionError: expected [OpenEMR] but found [CloudEMR]
at com.sg.test.LoginTest.validCredentialTest(LoginTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validCredentialTest -->
  <testcase classname="com.sg.test.LoginTest" name="validCredentialTest" time="4.021">
    <failure type="java.lang.AssertionError" message="expected [OpenEMR] but found [CloudEMR]">
      <![CDATA[java.lang.AssertionError: expected [OpenEMR] but found [CloudEMR]
at com.sg.test.LoginTest.validCredentialTest(LoginTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validCredentialTest -->
  <testcase classname="com.sg.test.LoginTest" name="validCredentialTest" time="4.032">
    <failure type="java.lang.AssertionError" message="expected [OpenEMR] but found [CloudEMR]">
      <![CDATA[java.lang.AssertionError: expected [OpenEMR] but found [CloudEMR]
at com.sg.test.LoginTest.validCredentialTest(LoginTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- validCredentialTest -->
</testsuite> <!-- Login Test - ff -->
